apiVersion: v1
kind: kbrew
app:
  repository:
    name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
    type: helm
  name: kube-prometheus-stack
  namespace: default
  sha256:
  version: 13.13.1
